### PR TITLE
Fixup JSON schemas

### PR DESCRIPTION
**Pull request by KellerFuchs**
- [x] Put `required` at the same level as `properties`, not under it.
- [x] Put properties definitions under `properties`.
- [x] Put regexps for validating IPv4 and IPv6 addresses.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
I'm half-tempted to say we shouldn't validate IP addresses in the JSON schema, because the regexps are simply too awful.

**Comment by KellerFuchs** [comment]
Ping?

**Comment by KellerFuchs** [comment]
@DeviaVir @RyanSquared @singlerider Any of you would have time to review this?

**Comment by DeviaVir** [comment]
@KellerFuchs sure thing, not sure how useful my opinion on this is though. What would validating the IPv4/IPv6 at this location give us vs. not doing it?
Code LGTM though.

**Review by RyanSquared — APPROVED** [review]
Not a fan of the regex, but if someone else approves I'll go along with it.

**Comment by KellerFuchs** [comment]
@DeviaVir Basically, enforcing the IP format there means that we enforce that we have valid IP addresses at all points (API client, API server, database).
It doesn't enforce that the IP addresses are the right ones, of course.

**Review by DeviaVir — APPROVED** [review]
Verified regex for ipv4 and ipv6 addresses, usage sounds useful to me.

**Review by lrvick — APPROVED** [review]

**Pull request merged**
